; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL    86400
@       IN      SOA     test.com root.localhost. (
                              1         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;

        IN      A       10.0.2.15
@       IN      NS      localhost.
test    IN      A       10.0.2.15
leaf1a  IN      A       10.0.0.99
leaf1b  IN      A       10.0.0.100
spine1  IN      A       10.0.0.101
spine2  IN      A       10.0.0.102
leaf1a  IN      A       10.0.0.103
leaf1b  IN      A       10.0.0.104

